name: Maven Test Pipeline

on:
  workflow_dispatch:

jobs:
  test-execution:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - uses: actions/checkout@v4

      - name: Download Maven
        run: wget https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip

      - name: Extract Maven
        run: unzip apache-maven-3.8.4-bin.zip -d maven

      - name: Run Maven Tests
        run: |
          export PATH=$PWD/maven/apache-maven-3.8.4/bin:$PATH
          mvn clean test -Dspring.profiles.active=dev -D spring.country.code=Latam -Dcucumber.filter.tags="@globalsonew and @latam" -Xmx3072m
        env:
          JAVA_HOME: /opt/java/jdk11.0.9.1

      - name: Upload Cucumber Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CucumberReports
          path: '**/results/**'

  parse-reports:
    needs: test-execution
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: CucumberReports
          path: ${{ github.workspace }}/artifact

      - name: Parse Reports
        run: bash gs-api/scripts/report-parser.sh
        env:
          ARTIFACT_DIRECTORY: ${{ github.workspace }}/artifact
          ENV: '-Dspring.profiles.active=dev -D spring.country.code=Latam'
          TAGS: '-Dcucumber.filter.tags="@globalsonew and @latam"'
